### ISSUE TITLE
Beveling?

### ISSUE THREAD

**Issue by SR-dude** [bwack/C64-250407-Replica-KiCad#8]
When placing the order for your shared project at pcbway, I was asked a question.  “You(me) chose “beveling” online but noted “not beveling “.  I checked and the default choice is “Yes at 30 degrees”. I don’t know how beveling could have been turned off. Did the gerbers do it?. What do you recommend?

**Comment by bwack** [comment]
Bevelling, as in making the pcb edge connectors chamfered at an angle is not possible to choose in gerber i think, therefore they ask.

Though they will probably get back to you and say that they can't do it because the pcb edge connectors are not far enough out on the edge. They told me otherwise the whole upper edge of the pcb would be bevelled. I guess they don't have a tool that can do only the connector, just the full edge if you know what mean.

**Comment by SR-dude** [comment]
I suppose I should leave beveling off then.
