### ISSUE TITLE
Orientation of the L4 choke

### ISSUE THREAD

**Issue by SR-dude** [bwack/C64-250407-Replica-KiCad#9]
I have a indented corner and on the opposite corner it reads "BL".  There are two orientations to fit this in L4. The indent is either pin 2 or pin 4. Do you know which?

**Comment by bwack** [comment]
I don't know your part, and BL I don't know. So you are asking if it is possible to mount is backwards ? It would work, as long as you don't mount it "side ways", then it would short the power supply.
Looking at the common mode chokes, the look very symmetrical though, so I wouldn't worry about the orientation other than having it pass current rather than shorting it. If it's an open design, you can see where the wires go, if not you can use a multimeter to find what pins are joined (measure a low resistance). I hope this helps.

**Comment by SR-dude** [comment]
I got it from a retro shop that  sells a c64 parts kit.  I think its a Kemet  SU10VD-10010. In any case, looking at it, it looks like that it is symmetrical. It's not square. So, there is only two ways to fit. Either will do.
